apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
#  nodeSelector:
#   kubernetes.io/hostname: ip-192-168-8-24.ec2.internal
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      prefferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference: 
        - matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value