apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx:alpine
---
apiVersion: v1
kind: Pod-1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
#  nodeSelector:
#   kubernetes.io/hostname: ip-192-168-8-24.ec2.internal
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - affinity
        topologyKey: topology.kubernetes.io/zone
---
apiVersion: v1
kind: Pod-2
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
#  nodeSelector:
#   kubernetes.io/hostname: ip-192-168-8-24.ec2.internal
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        labelSelector:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
        topologyKey: topology.kubernetes.io/zone